[build]
  publish = "website"

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/instructors"
  to = "/instructors.html"
  status = 200

[[redirects]]
  from = "/offerings"
  to = "/offerings.html"
  status = 200

[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200
