[build]
  publish = "website"

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/instructors"
  to = "/instructors.html"
  status = 200

[[redirects]]
  from = "/offerings"
  to = "/offerings.html"
  status = 200

[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/instructor-dashboard"
  to = "/instructor-dashboard.html"
  status = 200

# Redirects for deleted pages
[[redirects]]
  from = "/vision"
  to = "/offerings.html#flagships"
  status = 301

[[redirects]]
  from = "/vision.html"
  to = "/offerings.html#flagships"
  status = 301

[[redirects]]
  from = "/survey"
  to = "/community.html"
  status = 301

[[redirects]]
  from = "/survey.html"
  to = "/community.html"
  status = 301
