// Shared experiences data for EducatedTraveler
// Single source of truth — used by index.html quest selector and any future pages

window.ET_EXPERIENCES = [
    // ======== DIVING & OCEAN (PADI, AIDA, SSI, RYA) ========
    {
        id: 'scuba-mediterranean-cousteau',
        name: 'PADI Divemaster — French Mediterranean',
        category: 'diving',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['ocean'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 2,
        summary: 'Where Cousteau invented modern diving. Open Water to Divemaster on the Côte d\'Azur.',
        meta: '21-28 days · ~$6.5k-$8.5k · PADI Divemaster'
    },
    {
        id: 'freedive-dahab',
        name: 'AIDA Freediving Instructor — Dahab',
        category: 'diving',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 4500,
        maxPrice: 6500,
        envTags: ['ocean'],
        desireTags: ['certification', 'career', 'reset'],
        intensity: 3,
        summary: 'The Blue Hole. Where world records are set. AIDA 1-4 plus Instructor certification.',
        meta: '21-28 days · ~$4.5k-$6.5k · AIDA Instructor'
    },
    {
        id: 'ocean-sailing-rya-greece',
        name: 'RYA Day Skipper — Greek Islands',
        category: 'sailing',
        tier: 'foundation',
        minDays: 14,
        maxDays: 21,
        minPrice: 5500,
        maxPrice: 7500,
        envTags: ['ocean'],
        desireTags: ['certification', 'stories'],
        intensity: 2,
        summary: 'Cradle of Mediterranean sailing. RYA Day Skipper through the Cyclades.',
        meta: '14-21 days · ~$5.5k-$7.5k · RYA Day Skipper'
    },
    {
        id: 'ocean-sailing-atlantic',
        name: 'RYA Coastal Skipper — Atlantic Passage',
        category: 'sailing',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 7500,
        maxPrice: 9500,
        envTags: ['ocean'],
        desireTags: ['certification', 'stories', 'career'],
        intensity: 3,
        summary: 'Blue water passage across the Atlantic. RYA Coastal Skipper certification.',
        meta: '21-28 days · ~$7.5k-$9.5k · RYA Coastal Skipper'
    },
    {
        id: 'cave-diving-yucatan',
        name: 'PADI Cave Diver — Yucatan Cenotes',
        category: 'adventure',
        tier: 'mastery',
        minDays: 14,
        maxDays: 21,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['ocean'],
        desireTags: ['rare', 'stories', 'certification'],
        intensity: 3,
        summary: 'World\'s longest underwater cave systems. Full PADI Cave Diver certification.',
        meta: '14-21 days · ~$6.5k-$8.5k · PADI Cave Diver'
    },
    {
        id: 'kitesurfing-tarifa',
        name: 'IKO Kitesurfing Instructor — Tarifa',
        category: 'adventure',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 5500,
        maxPrice: 7500,
        envTags: ['ocean'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 3,
        summary: 'Wind capital of Europe. IKO Level 1 through Instructor certification.',
        meta: '21-28 days · ~$5.5k-$7.5k · IKO Instructor'
    },
    {
        id: 'surf-instructor-bali',
        name: 'ISA Surf Instructor — Bali',
        category: 'adventure',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 5500,
        maxPrice: 7500,
        envTags: ['ocean'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 2,
        summary: 'World-class breaks in Uluwatu and Canggu. ISA Level 1-2 Surf Instructor.',
        meta: '21-28 days · ~$5.5k-$7.5k · ISA Surf Instructor'
    },
    // ======== CULINARY (WSET, Le Cordon Bleu, ALMA) ========
    {
        id: 'pastry-le-cordon-bleu-paris',
        name: 'Le Cordon Bleu Pastry — Paris',
        category: 'culinary',
        tier: 'mastery',
        minDays: 30,
        maxDays: 60,
        minPrice: 15000,
        maxPrice: 25000,
        envTags: ['city'],
        desireTags: ['certification', 'career', 'creative'],
        intensity: 2,
        summary: 'The gold standard. Le Cordon Bleu Diplôme de Pâtisserie in Paris.',
        meta: '1-2 months · ~$15k-$25k · Le Cordon Bleu Diplôme'
    },
    {
        id: 'italian-cuisine-alma',
        name: 'ALMA Italian Cuisine — Parma',
        category: 'culinary',
        tier: 'mastery',
        minDays: 30,
        maxDays: 60,
        minPrice: 12000,
        maxPrice: 18000,
        envTags: ['city'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 2,
        summary: 'Italy\'s premier culinary school. ALMA professional certification in Parma.',
        meta: '1-2 months · ~$12k-$18k · ALMA Professional Certificate'
    },
    {
        id: 'wine-sommelier-bordeaux',
        name: 'WSET Level 3 — Bordeaux',
        category: 'culinary',
        tier: 'foundation',
        minDays: 14,
        maxDays: 21,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['city'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 1,
        summary: 'WSET Level 3 in the world\'s most legendary wine region. Château visits, cellar tastings.',
        meta: '14-21 days · ~$6.5k-$8.5k · WSET Level 3'
    },
    {
        id: 'sake-sommelier-niigata',
        name: 'SSI Sake Sommelier — Niigata',
        category: 'culinary',
        tier: 'foundation',
        minDays: 14,
        maxDays: 21,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['city'],
        desireTags: ['certification', 'rare', 'stories'],
        intensity: 1,
        summary: 'Japan\'s premier sake region. SSI Sake Sommelier certification with brewery immersion.',
        meta: '14-21 days · ~$6.5k-$8.5k · SSI Sake Sommelier'
    },
    // ======== WELLNESS (Yoga Alliance, ITM, WHM) ========
    {
        id: 'yoga-ryt200-rishikesh',
        name: 'Yoga Alliance RYT-200 — Rishikesh',
        category: 'wellness',
        tier: 'foundation',
        minDays: 25,
        maxDays: 28,
        minPrice: 5500,
        maxPrice: 6500,
        envTags: ['temple'],
        desireTags: ['certification', 'reset', 'career'],
        intensity: 2,
        summary: 'Birthplace of yoga. RYT-200 certification in ashrams on the Ganges.',
        meta: '25-28 days · ~$5.5k-$6.5k · Yoga Alliance RYT-200'
    },
    {
        id: 'yoga-ryt500-rishikesh',
        name: 'Yoga Alliance RYT-500 — Rishikesh',
        category: 'wellness',
        tier: 'mastery',
        minDays: 60,
        maxDays: 90,
        minPrice: 9500,
        maxPrice: 12000,
        envTags: ['temple'],
        desireTags: ['certification', 'career', 'reset'],
        intensity: 2,
        summary: 'Advanced teacher training at the source. RYT-500 for serious practitioners.',
        meta: '60-90 days · ~$9.5k-$12k · Yoga Alliance RYT-500'
    },
    {
        id: 'thai-massage-itm',
        name: 'ITM Thai Massage — Chiang Mai',
        category: 'wellness',
        tier: 'foundation',
        minDays: 14,
        maxDays: 21,
        minPrice: 3500,
        maxPrice: 4500,
        envTags: ['temple'],
        desireTags: ['certification', 'career', 'reset'],
        intensity: 1,
        summary: 'Original Thai massage tradition. ITM Level 1-3 certification from masters.',
        meta: '14-21 days · ~$3.5k-$4.5k · ITM Certification'
    },
    {
        id: 'breathwork-wim-hof',
        name: 'Wim Hof Method Instructor — Poland',
        category: 'wellness',
        tier: 'foundation',
        minDays: 7,
        maxDays: 14,
        minPrice: 4500,
        maxPrice: 6500,
        envTags: ['mountain'],
        desireTags: ['certification', 'reset', 'rare'],
        intensity: 3,
        summary: 'Train at the source with WHM Academy. Full instructor certification.',
        meta: '7-14 days · ~$4.5k-$6.5k · WHM Instructor'
    },
    // ======== WILDLIFE (FGASA) ========
    {
        id: 'safari-guide-fgasa',
        name: 'FGASA Safari Guide — South Africa',
        category: 'wildlife',
        tier: 'mastery',
        minDays: 55,
        maxDays: 55,
        minPrice: 9500,
        maxPrice: 12000,
        envTags: ['wild'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 2,
        summary: 'Industry gold standard. FGASA Level 1 Field Guide in the African bush.',
        meta: '55 days · ~$9.5k-$12k · FGASA Level 1'
    },
    {
        id: 'marine-guide-padi',
        name: 'PADI Marine Conservation — Great Barrier Reef',
        category: 'wildlife',
        tier: 'foundation',
        minDays: 21,
        maxDays: 28,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['ocean', 'wild'],
        desireTags: ['certification', 'stories', 'career'],
        intensity: 2,
        summary: 'Largest coral reef on Earth. PADI Coral Reef Conservation specialty certification.',
        meta: '21-28 days · ~$6.5k-$8.5k · PADI Specialty'
    },
    // ======== ADVENTURE SPORTS (IFMGA, ACA) ========
    {
        id: 'mountaineering-chamonix',
        name: 'IFMGA Alpinism — Chamonix',
        category: 'adventure',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 7500,
        maxPrice: 9500,
        envTags: ['mountain'],
        desireTags: ['certification', 'stories', 'rare'],
        intensity: 3,
        summary: 'Birthplace of alpinism. Train with IFMGA guides toward aspirant certification.',
        meta: '21-28 days · ~$7.5k-$9.5k · IFMGA Aspirant'
    },
    {
        id: 'kayak-instructor-costa-rica',
        name: 'ACA Whitewater Instructor — Costa Rica',
        category: 'adventure',
        tier: 'mastery',
        minDays: 21,
        maxDays: 28,
        minPrice: 5500,
        maxPrice: 7500,
        envTags: ['ocean', 'wild'],
        desireTags: ['certification', 'career', 'stories'],
        intensity: 3,
        summary: 'Class III-V rapids in the jungle. ACA Level 4 Whitewater Kayak Instructor.',
        meta: '21-28 days · ~$5.5k-$7.5k · ACA Level 4 Instructor'
    },
    // ======== SAGA EXPERIENCES ========
    {
        id: 'ocean-sailing-odyssey-saga',
        name: 'RYA Yachtmaster — 90-Day Saga',
        category: 'sailing',
        tier: 'saga',
        minDays: 90,
        maxDays: 90,
        minPrice: 28000,
        maxPrice: 28000,
        envTags: ['ocean'],
        desireTags: ['career', 'stories', 'certification'],
        intensity: 3,
        summary: 'Day Skipper through Yachtmaster Offshore. 90 days of ocean passages.',
        meta: '90 days · ~$28k · RYA Yachtmaster Offshore'
    },
    {
        id: 'dive-pro-saga',
        name: 'PADI Instructor Development — 90-Day Saga',
        category: 'diving',
        tier: 'saga',
        minDays: 90,
        maxDays: 90,
        minPrice: 15000,
        maxPrice: 18000,
        envTags: ['ocean'],
        desireTags: ['career', 'certification', 'stories'],
        intensity: 2,
        summary: 'Open Water to PADI Instructor. Mediterranean training with IDC and IE.',
        meta: '90 days · ~$15k-$18k · PADI Open Water Scuba Instructor'
    },
    // ======== NEW CULINARY EXPERIENCES ========
    {
        id: 'ferrandi-pastry-paris',
        name: 'Ferrandi French Pastry — Paris',
        category: 'culinary',
        tier: 'mastery',
        minDays: 30,
        maxDays: 60,
        minPrice: 12000,
        maxPrice: 18000,
        envTags: ['city'],
        desireTags: ['certification', 'career', 'creative'],
        intensity: 2,
        summary: 'The school that trained Paris\'s finest pastry chefs. Ferrandi professional certificate.',
        meta: '1-2 months · ~$12k-$18k · Ferrandi Certificate'
    },
    {
        id: 'modernist-cuisine-barcelona',
        name: 'Modernist Cuisine — Barcelona',
        category: 'culinary',
        tier: 'mastery',
        minDays: 30,
        maxDays: 60,
        minPrice: 12000,
        maxPrice: 18000,
        envTags: ['city'],
        desireTags: ['certification', 'career', 'rare'],
        intensity: 2,
        summary: 'Molecular gastronomy and avant-garde techniques. Hofmann Barcelona professional diploma.',
        meta: '1-2 months · ~$12k-$18k · Hofmann Diploma'
    },
    {
        id: 'indigenous-mexican-oaxaca',
        name: 'Indigenous Mexican Cuisine — Oaxaca',
        category: 'culinary',
        tier: 'foundation',
        minDays: 21,
        maxDays: 28,
        minPrice: 6500,
        maxPrice: 8500,
        envTags: ['city'],
        desireTags: ['certification', 'stories', 'rare'],
        intensity: 2,
        summary: 'Pre-Hispanic techniques with local masters. Mezcal, mole, and ancient traditions in the culinary heart of Mexico.',
        meta: '21-28 days · ~$6.5k-$8.5k · CESSA Professional Certificate'
    }
];

window.ET_PERSONAS = {
    sailing: {
        title: 'Ocean Tactician',
        subtitle: 'You think in wind shifts and watch rotations. The sea is a moving chessboard.'
    },
    diving: {
        title: 'Blue Depth Seeker',
        subtitle: 'You know the best things happen below the surface.'
    },
    wellness: {
        title: 'Quiet Storm',
        subtitle: 'You want the kind of calm that survives real life, not just retreats.'
    },
    culinary: {
        title: 'Kitchen Alchemist',
        subtitle: 'Precise, obsessive, willing to repeat the same cut a thousand times.'
    },
    adventure: {
        title: 'Edgewalker',
        subtitle: 'You chase the edge to see who you become on the other side of fear.'
    },
    wildlife: {
        title: 'Wild Guide',
        subtitle: 'You\'d rather track animals than trends.'
    }
};
