/* Studio "Ideas" tab data — the ready-to-shoot first-10 shot list + the creative
 * library (hooks, recurring series, save/share triggers, never-post).
 * Source: marketing/daily-drop/SHOT-LIST-first10.md + CONTENT-IDEA-BANK.md.
 * Captions are paste-ready and voice-locked (no banned words, no prices). */
window.ET_IDEAS = {
  shotList: [
    {
      n: 1, core: "culinary", craft: "Sushi & Washoku", place: "Tokyo (Tsukiji / Toyosu), Japan",
      atlasUrl: "https://educatedtraveler.app/atlas/sushi-and-washoku--tokyo-tsukiji-toyosu",
      footage: "Chef-shootable (you) — or license Tokyo Sushi Academy", placeCard: "Tokyo, Japan", lead: false,
      beats: [
        "Macro top-down: warm rice cradled in the palm, pressed into a single soft pillow (the 6 seconds that matter).",
        "A swipe of wasabi onto the fish.",
        "Tuna laid over; two-finger press; the 90° turn and second press.",
        "B-roll: the row filling out along the geta board.",
      ],
      ending: "the last nigiri set down at the end of a perfectly even, fish-gleaming row.",
      sound: "the pat of rice, the blade, a quiet room.", cover: "the two-finger press at its apex.",
      caption: "This is where edomae sushi was born.\n\nStand beside the world's most demanding fish market and earn the craft the way Jiro Ono's lineage still teaches it — by hand, by repetition, at the source.\n\nCommunity strength: Legendary. Season: Year-round (peak Mar–May, Sep–Nov).\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/sushi-and-washoku--tokyo-tsukiji-toyosu",
      hashtags: "#foodtok #sushichef #learnbydoing #tokyo #edomaesushi",
    },
    {
      n: 2, core: "culinary", craft: "French Pastry & Patisserie", place: "Paris, France",
      atlasUrl: "https://educatedtraveler.app/atlas/french-pastry-and-patisserie--paris",
      footage: "Chef-shootable (you) — or license FERRANDI Paris", placeCard: "Paris, France", lead: false,
      beats: [
        "Tight on the piping bag: one breath, a flawless ring of choux, the wrist-flick cut.",
        "Warm mirror glaze poured over a frozen entremets, sheeting and self-levelling to a reflective gloss.",
        "A palette knife lifting the glazed entremets clean.",
      ],
      ending: "the entremets set on the gold board, mirror surface intact, reflecting the window light.",
      sound: "the squeeze of the bag, the pour, the scrape.", cover: "the glaze mid-sheet, light catching the gloss.",
      caption: "Paris is still the living capital of French pastry.\n\nStand at the bench where the CAP Pâtissier was forged and learn the diploma the rest of the world measures itself against — the road that ends at Meilleur Ouvrier de France.\n\nCommunity strength: Legendary. Season: Sep–Jun.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/french-pastry-and-patisserie--paris",
      hashtags: "#foodtok #pastrychef #learnbydoing #paris #frenchpastry",
    },
    {
      n: 3, core: "culinary", craft: "Bread & Boulangerie", place: "Paris, France",
      atlasUrl: "https://educatedtraveler.app/atlas/bread-and-boulangerie--paris",
      footage: "Chef-shootable (you) — or license EBP Paris", placeCard: "Paris, France", lead: false,
      beats: [
        "Slack levain stretched to a translucent windowpane between the fingers.",
        "The lame scoring one fast, confident arc down the shaped dough.",
        "In-oven (or close on the cooling rack): the ear blooming open.",
      ],
      ending: "the baguette de tradition snapped over the lens — crust-shatter, steaming open honeycomb crumb. Use the crackle.",
      sound: "the score, the oven, the crust crackling.", cover: "the lame mid-arc.",
      caption: "Paris is still the living capital of bread.\n\nHome of the CAP Boulanger and the baguette de tradition — earn your levain where the craft's modern rules were written.\n\nCommunity strength: Legendary. Season: Sep–Jun.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/bread-and-boulangerie--paris",
      hashtags: "#foodtok #sourdough #learnbydoing #paris #boulangerie",
    },
    {
      n: 4, core: "adventure", craft: "Scuba Diving", place: "Koh Tao, Thailand",
      atlasUrl: "https://educatedtraveler.app/atlas/scuba-diving--koh-tao",
      footage: "Waterman-shootable (you) — or license Crystal Dive", placeCard: "Koh Tao, Thailand", lead: false,
      beats: [
        "Hands running the pre-dive buddy check (reg purge hiss, weight-belt buckle snap).",
        "The giant-stride entry: one hand pinning mask + reg, the white explosion of bubbles, the clear.",
        "Descent: the diver settling into the blue.",
      ],
      ending: "the diver dead-still in a neutral mid-water hover, slowly signalling OK.",
      sound: "the reg hiss, the splash, then breathing underwater.", cover: "the giant-stride mid-bubble-burst.",
      caption: "More divers are certified on this one granite island than almost anywhere on Earth.\n\nArrive able to swim and leave a working Divemaster, inside a real instructor cohort — Open Water to pro, where the whole world comes to learn.\n\nCommunity strength: Legendary. Season: Year-round (best Mar–Sep).\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/scuba-diving--koh-tao",
      hashtags: "#adventuretravel #scubadiving #learnbydoing #kohtao #divemaster",
    },
    {
      n: 5, core: "adventure", craft: "Freediving", place: "Dahab (Red Sea), Egypt",
      atlasUrl: "https://educatedtraveler.app/atlas/freediving--dahab-red-sea",
      footage: "YOU — your breath, your proof", placeCard: "Dahab, Egypt", lead: true,
      beats: [
        "Surface, straight down the line: two purge breaths fogging the surface, the peak inhale.",
        "The silent, splashless duck-dive; the silhouette shrinking into the dark.",
        "The turn on the line / the rise back toward the light.",
      ],
      ending: "frozen on the OK hand against the blue, after one clean recovery breath. (The held breath is the rewatch.)",
      sound: "the breathe-up, then near-silence and the heartbeat of water.", cover: "the duck-dive, body folding past vertical.",
      caption: "The strongest freediving community on earth gathers around Dahab's Blue Hole.\n\nFlat, deep and warm all year, the current-free Blue Hole is where the world's freedivers go to find depth — and find their cohort. AIDA and Molchanovs, level by level.\n\nCommunity strength: Legendary. Season: Year-round.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/freediving--dahab-red-sea",
      hashtags: "#freediving #adventuretravel #learnbydoing #dahab #bluehole",
    },
    {
      n: 6, core: "culinary", craft: "Chocolate & Confectionery", place: "Tain-l'Hermitage, France",
      atlasUrl: "https://educatedtraveler.app/atlas/chocolate-and-confectionery--tain-l-hermitage",
      footage: "Chef-shootable (you) — or license L'École Valrhona", placeCard: "Tain-l'Hermitage, France", lead: false,
      beats: [
        "Dark couverture spread and gathered on the marble slab, tabling to a satin temper.",
        "A bonbon centre dipped, tapped to shed a clean curtain of chocolate.",
        "The shells lined up, setting matte-to-glossy.",
      ],
      ending: "the SNAP of a set bonbon, revealing the glossy interior and clean shell.",
      sound: "the scrape on marble, the tap, the snap.", cover: "the dipped bonbon mid-curtain.",
      caption: "Tain-l'Hermitage is still the living capital of fine chocolate.\n\nTemper grand-cru couverture in Valrhona's home valley, at the atelier that taught the world how French fine chocolate is made.\n\nCommunity strength: Legendary. Season: Year-round.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/chocolate-and-confectionery--tain-l-hermitage",
      hashtags: "#foodtok #chocolatier #learnbydoing #valrhona #finechocolate",
    },
    {
      n: 7, core: "adventure", craft: "Sailing & Yachtmaster", place: "The Solent, UK",
      atlasUrl: "https://educatedtraveler.app/atlas/sailing-and-yachtmaster--the-solent-cowes-and-hamble",
      footage: "Waterman-shootable (you) — or license UKSA", placeCard: "The Solent, England", lead: false,
      beats: [
        "Sheet wrapped three times, winch handle dropped in, cranking until the genoa snaps taut and the boat leaps.",
        "The helm eased as the rail goes down, water racing the leeward side.",
        "Hands on the wheel finding the groove.",
      ],
      ending: "telltales streaming flat, the wake dead straight, the helmsman's hand calm. Wind and water only.",
      sound: "the winch clicks, the snap of the sail, the bow wave.", cover: "the rail-down moment, spray flying.",
      caption: "The Solent forged the most respected ticket afloat — earned, never bought.\n\nThis is where the RYA built its Yachtmaster scheme, and its tidal chaos still examines you the hard way: the offshore certificate the whole industry trusts.\n\nCommunity strength: Legendary. Season: Apr–Oct.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/sailing-and-yachtmaster--the-solent-cowes-and-hamble",
      hashtags: "#sailing #yachtmaster #learnbydoing #thesolent #rya",
    },
    {
      n: 8, core: "culinary", craft: "Asado & Open-Fire Cooking", place: "Patagonia / Buenos Aires, Argentina",
      atlasUrl: "https://educatedtraveler.app/atlas/asado-and-open-fire-cooking--patagonia-buenos-aires",
      footage: "Chef-shootable (you) — or license a Mallmann/estancia clip", placeCard: "Patagonia, Argentina", lead: false,
      beats: [
        "A whole lamb on the iron cross over embers; the coals raked underneath (the reading of the fire).",
        "Fat dripping and flaring; a brine brush sweeping across the skin.",
        "Wide: the cross against the open sky.",
      ],
      ending: "at dusk — the cross tilted to camera, lamb bronzed and blistered, a knife pulling the first piece, fire behind.",
      sound: "the crackle of fire, the drip-and-flare, wind.", cover: "a flare licking up the lamb.",
      caption: "Argentina is the home of asado.\n\nOn gaucho estancias the whole lamb slow-cooks on the iron cross, and Francis Mallmann turned seven kinds of fire into a discipline studied worldwide. Learn to build and read the fire.\n\nCommunity strength: Legendary. Season: Nov–Mar.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/asado-and-open-fire-cooking--patagonia-buenos-aires",
      hashtags: "#foodtok #asado #learnbydoing #argentina #livefire",
    },
    {
      n: 9, core: "adventure", craft: "Surfing", place: "Waikiki, Oahu",
      atlasUrl: "https://educatedtraveler.app/atlas/surfing--waikiki-oahu",
      footage: "Waterman-shootable (you) — or license Hans Hedemann Surf", placeCard: "Waikiki, Hawai'i", lead: false,
      beats: [
        "A hand circling fresh wax until the bumps rise on the deck.",
        "Low water-level paddle-out.",
        "The pop-up: palms press, back foot swings, body rises, trimming a long rolling right with Diamond Head behind.",
      ],
      ending: "the long, calm glide all the way to the inside — not a turn, just being carried. Board-hiss only.",
      sound: "the wax circling, the paddle, the hiss of the board on the face.", cover: "the pop-up at full extension.",
      caption: "He'e nalu was born on these rolling rights.\n\nTo learn at the source where Duke Kahanamoku carried surfing to the world is the pilgrimage every surfer owes the sea.\n\nCommunity strength: Legendary. Season: Year-round (summer south swell for learners).\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/surfing--waikiki-oahu",
      hashtags: "#surfing #learntosurf #learnbydoing #waikiki #heenalu",
    },
    {
      n: 10, core: "wellness", craft: "Pranayama & Breathwork", place: "Lonavla, India",
      atlasUrl: "https://educatedtraveler.app/atlas/pranayama-and-breathwork--lonavla",
      footage: "YOU — your breath, your hands", placeCard: "Lonavla, India", lead: true,
      beats: [
        "Tight on one hand: vishnu mudra closing one nostril then the other in slow nadi shodhana, the chest rising.",
        "A beat of kapalabhati: the belly snapping in on each sharp exhale.",
        "Settle to stillness.",
      ],
      ending: "the held retention — chest utterly still — and one soft release. Breath is the only track.",
      sound: "only the breath.", cover: "the hand at the mudra, chest at full inhale.",
      caption: "The world's oldest scientific yoga research institute, founded 1924.\n\nWhere pranayama was first put under the microscope and is still taught from the original texts — learn the breath at the source, in the Kaivalyadhama lineage.\n\nCommunity strength: Legendary. Season: Oct–Mar.\nWe map where every craft is truly alive — and introduce you to the school and the people going.\nThe full page: https://educatedtraveler.app/atlas/pranayama-and-breathwork--lonavla",
      hashtags: "#breathwork #pranayama #learnbydoing #lonavla #yoga",
    },
  ],

  hooks: [
    { name: "The Source", template: "This is where {craft} was born.", example: "This is where glassblowing was born." },
    { name: "Living Capital", template: "{place} is still the living capital of {craft}.", example: "Paris is still the living capital of French pastry." },
    { name: "Strongest Community", template: "The strongest {craft} community on earth gathers in {place}.", example: "…gathers around Dahab's Blue Hole." },
    { name: "Before → Competence", template: "You arrive a tourist. You leave able to {competent act}.", example: "…leave able to roll a sheet of pasta thin enough to read through. Bologna." },
    { name: "Can't-do-from-a-screen", template: "No screen can teach your hands {tactile thing}. Only {place} can.", example: "…the moment hot glass stops being liquid and starts being yours. Only Murano." },
    { name: "The People Here", template: "In {place}, the {people} who guard {craft} still teach it by hand.", example: "…the sfogline who guard hand-rolled pasta still teach it the way their grandmothers did." },
    { name: "The Number", template: "{number/date} — {what it measures}, all traceable to {place}.", example: "1291 — the year Venice exiled its furnaces to one island and never let the secrets leave." },
    { name: "The Season Window", template: "{craft} in {place} only opens for {season} — then the cohort scatters.", example: "Yosemite's big-wall season runs Apr–Oct — then the granite cohort scatters." },
    { name: "Hands of a Master", template: "This is the hand that {signature move} — {master}, {place}.", example: "…closes a tortellino in under two seconds without looking — a Bolognese sfoglina." },
    { name: "One Unbroken Lineage", template: "Every {practitioner} on earth traces back to one room in {place}.", example: "Every certified Iyengar teacher traces back to one room in Pune." },
  ],

  series: [
    { name: "The Source", note: "Birthplaces only — \"This is where X was born.\" The strongest authority + scarcity claim you own." },
    { name: "One Breath", note: "A single uncut held breath or descent (freediving, pranayama, cold). Minimal cuts; forces watch-time. Most founder-true." },
    { name: "The Finished Object", note: "Cold-open the payoff in the first 0.5s, then the making, ending back on it. The most reliable scroll-stopper." },
    { name: "Hands of a Master", note: "One named master's signature move, isolated and repeated. A name turns a craft into a person — and the master may repost." },
    { name: "The First Time", note: "A true beginner's first competent rep. The strongest \"this could be me\" save and \"we should do this\" send." },
    { name: "Where the People Are", note: "The room, not the soloist — a hall breathing in unison, a dive cohort kitting up. Answers \"would I be alone?\" Drives the Circle." },
    { name: "The Window", note: "Posted only when a craft's season is open. The most honest urgency you can use (no prices, no \"book now\")." },
    { name: "The Quiet Ones", note: "The calm, near-silent clip (meditation, calligraphy, a hand plane). On a feed of spikes, calm is contrast — your highest saves." },
  ],

  saveTriggers: [
    "End on competence, never the action — the brain saves the payoff. Make the last half-second the most beautiful frame.",
    "Cold-open the payoff so the first 0.5s shows where it's going — it earns the re-watch (re-watches compound watch-time).",
    "Build in ONE \"how did they do that\" impossible second — that second is the shareable unit. Cut everything that isn't building to it.",
    "Make it answerable, not just watchable — source-vs-scene or a season window invites the comment (\"source every time\").",
    "Trigger \"this could be me\" (The First Time) and \"send this to my person\" (Where the People Are — group clips travel into DMs).",
    "Keep it wordless; mix the foley loud and clean; never bury the craft's own sound under music.",
    "First caption line = a standalone copy-pasteable FACT (birthplace, date, record). Facts get screenshotted and quote-shared.",
    "Anchor to exactly ONE Atlas URL + ONE place card. \"Somewhere in Italy\" isn't saveable; \"Murano + the page\" is a plan.",
  ],

  neverPost: [
    "Talking-head explainers / founder narrating to camera as a feed post — kills the wordless premium and the global reach.",
    "Listicles / \"top 10 places to learn X\" — the soulless skillcation look; points at no single Atlas page.",
    "Sell / price / \"book now\" / \"enroll\" / \"link in bio to checkout\" — breaks the voice lock; nobody forwards an ad.",
    "Polished travel-brochure montages (drone sweeps, sunset b-roll, models) — reads as an ad, no tactile hook.",
    "Format fragmentation before day 90 (trends, music, dances, on-screen-text) — resets the algorithm's learning.",
    "Regional / per-discipline account splits — fragments the cadence signal. One global account feeds all three platforms.",
    "Watermark-reposting (re-upload a watermarked TikTok) — IG downranks it; YouTube can throttle the channel. Native, clean master only.",
    "Text walls, captions burned over the action, or trending-audio music beds — buries the foley that drives watch-time.",
  ],
};
